"""
Django settings for clubsite project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import mimetypes
import environ

env = environ.Env()
environ.Env.read_env()
# from django.utils.translation import gettext as _



mimetypes.add_type("text/css", ".css", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

SITE_ID = 1

SCHED_WEBSITE_URL = env('SITE_SCHED_WEBSITE_URL')

ALLOWED_HOSTS = [env('SITE_ALLOWED_HOSTS')]


# Application definition

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'django.contrib.staticfiles',
    'home.apps.HomeConfig',
    'pages.apps.PagesConfig',
    'ads.apps.AdsConfig',
    'tables.apps.TablesConfig',
    'blast.apps.BlastConfig',
    'reports.apps.ReportsConfig',
    'certificates.apps.CertificatesConfig',
    'badges.apps.BadgesConfig',
    'invoices.apps.InvoicesConfig',
    'keys.apps.KeysConfig',
    'minutes.apps.MinutesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.postgres',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    # pip installed apps
    'sass_processor',
    'schedule',
    'djangobower',
    'jquery',
    'jquery_ui',
    'bootstrap4',
    'userena',
    'guardian',
    'easy_thumbnails',
    'sorl.thumbnail',
    'address',
    'phone_field',
    'crispy_forms',
    'crispy_bootstrap5',
    'contact_form',
    'public_form',
    'django_extensions',
    'newsletter',
    'tinymce',
    'captcha',
    'photologue',
    'sortedm2m',
]

BOWER_INSTALLED_APPS = (
    'jquery',
    'jquery-ui',
    'bootstrap'
)

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clubsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'minutes.custom_context_processor.post_minutes_renderer',
                'blast.custom_context_processor.occurrences_this_week_index',
                'blast.custom_context_processor.events_renderer',
                'blast.custom_context_processor.ctx_occurrence_model',
                'blast.custom_context_processor.occurrences_this_week',
                'pages.custom_context_processor.events_renderer',
                'pages.custom_context_processor.my_map',
                'pages.custom_context_processor.certificates_renderer',
                'pages.custom_context_processor.certificates_not_sale_renderer',
                'pages.custom_context_processor.members_renderer',
                'pages.custom_context_processor.birthdays_renderer',
                'pages.custom_context_processor.occurrences_this_week_index',
                'pages.custom_context_processor.occurrences_this_week',
                'pages.custom_context_processor.occurrences_next_thirty',
                'pages.custom_context_processor.occurrences_next_sixty',
                'pages.custom_context_processor.occurrences_next_ninety',
                'pages.custom_context_processor.occurrences_next_twohundred',
                'pages.custom_context_processor.occurrences_year',
                'pages.custom_context_processor.ctx_volunteer_form',
                'pages.custom_context_processor.ctx_occurrence_model',
                'pages.custom_context_processor.ctx_volunteer_model',
                'pages.custom_context_processor.ctx_memberrsvp_model',
                'pages.custom_context_processor.volunteer_renderer',
                'pages.custom_context_processor.memberrsvp_renderer',
                'pages.custom_context_processor.ctx_memberrsvp_form',
                'pages.custom_context_processor.feature_renderer',
                'pages.custom_context_processor.alert_renderer',
                'pages.custom_context_processor.activity_bulletin_board_renderer',
                'badges.custom_context_processor.badge_renderer',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'clubsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DATABASE_ENGINE'),
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASS'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
        },
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'userena.backends.UserenaAuthenticationBackend',
    'guardian.backends.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = True
EMAIL_HOST = env('SITE_EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_HOST_USER = env('SITE_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('SITE_EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = env('SITE_DEFAULT_FROM_EMAIL')

ADMINS = (
    (
        env('SITE_ADMIN_ONE'), env('SITE_ADMIN_TWO')
    ),
)

# email will be sent to your_email

MANAGERS = ADMINS


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Phoenix'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATE_INPUT_FORMATS = ['%m-%d-%Y']

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
    'sass_processor.finders.CssFinder',
]

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
)


BOWER_COMPONENTS_ROOT = 'home/coyotelakes/clubsite/static/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

MEDIA_ROOT = '/home/coyotelakes/clubsite/media'
MEDIA_URL = '/media/'
STATIC_ROOT = '/home/coyotelakes/clubsite/static'
STATIC_URL = '/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TIME_INPUT_FORMATS = ('%I:%M %p',)



# ----------------These are the settings for django-userena-ce

# AUTH_PROFILE_MODULE = 'UserenaBaseProfile'


'''  See setting descriptions here:  https://django-userena-ce.readthedocs.io/en/latest/settings.html#settings '''
AUTH_PROFILE_MODULE = 'accounts.MyProfile'
USERENA_SIGNIN_AFTER_SIGNUP = False
USERENA_SIGNIN_REDIRECT_URL = '/accounts/%(username)s/'
USERENA_ACTIVATION_REQUIRED = True
# default for activation required is true and requires more settings  See documentation
# here are the extra settings for activation required
USERENA_ACTIVATION_DAYS = 7
USERENA_ACTIVATION_NOTIFY = True
USERENA_ACTIVATION_NOTIFY_DAYS = 2
USERENA_ACTIVATION_RETRY = False
# ^^ end extra settings for activation
USERENA_ACTIVATED = 'ALREADY_ACTIVATED'
# USERENA_REMEMBER_ME_DAYS = (_('a month'), 30)
USERENA_MUGSHOT_GRAVATAR = True
USERENA_MUGSHOT_DEFAULT = 'mm'
# there are a few options to choose from here. ^^ See documentation
USERENA_MUGSHOT_SIZE = 430
USERENA_MUGSHOT_PATH = 'mugshots/%(username)s/'
USERENA_USE_HTTPS = True

# Change below if I want users to see each other's profiles.  closed, registered, open, are choices
USERENA_DEFAULT_PRIVACY = 'registered'
USERENA_PROFILE_DETAIL_TEMPLATE = 'userena/profile_detail.html'
USERENA_PROFILE_LIST_TEMPLATE = 'userena/profile_list.html'
USERENA_DISABLE_PROFILE_LIST = False
USERENA_DISABLE_SIGNUP = False
# I may want to disable sign up for this site since all users will be entered in.
USERENA_USE_MESSAGES = True
USERENA_LANGUAGE_FIELD = 'language'
USERENA_WITHOUT_USERNAMES = False
USERENA_HIDE_EMAIL = False
USERENA_HTML_EMAIL = True
# ^^ if true, multipart emails are generated using html templates
USERENA_USE_PLAIN_TEMPLATE = True
USERENA_REGISTER_PROFILE = True
''' If True userena will register the profile model with Django Admin for you.
It uses a GuardedModelAdmin when registering. This allows per user object permissions
to be set via the admin. If False you will have to regiter the profile
with the Django Admin yourself.'''
USERENA_REGISTER_USER = True
''' If True userena will first unregister the user model with the
admin and then reregister the user model using a GuardedModelAdmin.
This allows you to set per user object permissons. If False and you
want to you set per user object permissions on the user model via
the admin you will have to unregister and reregiter the user model
with the Django Admin yourself. '''

ANONYMOUS_USER_NAME = env('SITE_ANONYMOUS_USER_NAME')

AUTH_PROFILE_MODULE = 'accounts.MyProfile'

USERENA_SIGNIN_REDIRECT_URL = '/accounts/%(username)s/'

# ------------ end userena settings -------------

# ---------- begin contact_form settings -----------https://django-contact-form.readthedocs.io/en/1.9/quickstart.html
# Add the akismet key if you want spam protection. Lowest cost $12 a year.  https://akismet.com/signup/#personal
# PYTHON_AKISMET_API_KEY = akismet_settings.PYTHON_AKISMET_API_KEY

# PYTHON_AKISMET_BLOG_URL


# ---------- end contact_form settings



LOGIN_URL = '/accounts/signin/'
LOGOUT_URL = '/accounts/signout/'

from . import google_settings
GOOGLE_API_KEY = google_settings.GOOGLE_API_KEY



''' These are django-newsletter settings '''

# Using easy-thumbnails
NEWSLETTER_THUMBNAIL = 'easy-thumbnails'

NEWSLETTER_CONFIRM_EMAIL = False


# Using django-tinymce
NEWSLETTER_RICHTEXT_WIDGET = "tinymce.widgets.TinyMCE"

# Amount of seconds to wait between each email. Here 100ms is used.
NEWSLETTER_EMAIL_DELAY = 0.5

# Amount of seconds to wait between each batch. Here one minute is used.
NEWSLETTER_BATCH_DELAY = 300

# Number of emails in one batch
NEWSLETTER_BATCH_SIZE = 50

TINYMCE_DEFAULT_CONFIG = {
    # URL settings
    'convert_urls' : False,
    'relative_urls' : False,
    'height':'480px',
}

# This frame options thing was so we can see the preview in the admin panel

X_FRAME_OPTIONS = 'SAMEORIGIN'

CAPTCHA_2X_IMAGE = True
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_null','captcha.helpers.noise_dots',)
