# Generated by Django 3.2.6 on 2021-08-11 22:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minutes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostMinutes',
            new_name='PostMinute',
        ),
    ]
