# Generated by Django 3.2.6 on 2021-08-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0003_postminute_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postminute',
            name='body',
            field=models.TextField(help_text='Include only the body of the minutes (without the list of attendees and date).'),
        ),
        migrations.AlterField(
            model_name='postminute',
            name='title',
            field=models.CharField(help_text="Please use this format: 'Month Date Year Board Meeting'.", max_length=250),
        ),
    ]
