# Generated by Django 3.2.6 on 2021-08-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0004_auto_20210813_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postminute',
            name='attendance',
            field=models.TextField(blank=True, help_text='Example: Board members present: John Smith, Mary Jones, Jane Doe.  Approximately 30 members present.'),
        ),
        migrations.AlterField(
            model_name='postminute',
            name='body',
            field=models.TextField(help_text='Include only the body of the minutes (without the list of attendees and date.  **header** will show up as bold type. A dash (-) before items in a list will format as a list.).'),
        ),
    ]
