# Generated by Django 3.2.6 on 2021-08-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0005_auto_20210813_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postminute',
            name='body',
            field=models.TextField(help_text='Include only the body of the minutes (without the list of attendees and date).  **header** will show up as bold type. A dash (-) before items in a list will format as a list.'),
        ),
    ]
