# Generated by Django 3.2.6 on 2021-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0006_alter_postminute_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postminute',
            name='title',
            field=models.CharField(help_text="Please use this format: 'Month Date Year Board Meeting'. NO COMMA, PLEASE", max_length=250),
        ),
    ]
