# Generated by Django 3.2.6 on 2021-08-13 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0009_alter_postminute_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postminute',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enter the date that the meeting occured.  Time should be 06:00 am'),
        ),
        migrations.AlterField(
            model_name='postminute',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text="Select 'Published' for it to appear on the web site.", max_length=10),
        ),
    ]
