# Generated by Django 3.2.6 on 2021-09-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0010_auto_20210813_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postminute',
            name='body',
            field=models.TextField(help_text='Include only the body of the minutes (without the list of attendees and date).  To make a link use this format: [text](full website address) **text** will show up as bold type. A dash (-) before items in a list will format as a list.'),
        ),
    ]
