# Generated by Django 3.2.6 on 2022-01-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0011_alter_postminute_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='postminute',
            name='pdf',
            field=models.FileField(blank=True, help_text='please upload .pdf file of meeting minutes.', null=True, upload_to='minutes/pdf/'),
        ),
        migrations.AddField(
            model_name='postminute',
            name='recording',
            field=models.FileField(blank=True, help_text='please upload audio recording in .mp3 or .m4a format. If you need another format, please let Marci know.', null=True, upload_to='minutes/audio/'),
        ),
    ]
