# Generated by Django 3.2.6 on 2022-01-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0012_auto_20220104_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postminute',
            old_name='recording',
            new_name='audio_recording',
        ),
        migrations.AddField(
            model_name='postminute',
            name='video_recording',
            field=models.FileField(blank=True, help_text='please upload video recording in .mp4 format. If you need another format, please let Marci know.', null=True, upload_to='minutes/video/'),
        ),
    ]
