# Generated by Django 3.2.6 on 2022-01-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0013_auto_20220104_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postminute',
            name='audio_recording',
            field=models.FileField(blank=True, help_text='Max file size: 100MB. Please upload audio recording in .mp3 or .m4a format. If you need another format, please let Marci know.', null=True, upload_to='minutes/audio/'),
        ),
        migrations.AlterField(
            model_name='postminute',
            name='video_recording',
            field=models.FileField(blank=True, help_text='Max file size: 100MB. Please upload video recording in .mp4 format. If you need another format, please let Marci know.', null=True, upload_to='minutes/video/'),
        ),
    ]
