# Generated by Django 3.2.6 on 2022-01-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0014_auto_20220104_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='postminute',
            name='video_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='postminute',
            name='video_url_link',
            field=models.URLField(blank=True, help_text='Use this to provide a link to a video of the meeting that resides elsewhere (Such as Google Drive). Use complete url (e.g. https://drive.google.com/file/d/1RsePz_IBDLr_vajMBzo_h_6yhQUtdfRW/view?usp=sharing', max_length=300, null=True),
        ),
    ]
