# Generated by Django 3.2.6 on 2022-02-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(blank=True, help_text='Enter the certificate name (usually person or entity who is selling it).', max_length=100, null=True)),
                ('date_resigned', models.DateField(blank=True, default='', help_text='Enter date of the certificate resignation.', null=True)),
                ('sold_to', models.CharField(blank=True, help_text='Enter the name of the person or entity the certificate was sold to. If there is no name in this blank, the certificate will appear in the for sale table on the website.', max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, default='', help_text='Enter date the certificate/membership was sold.', null=True)),
                ('for_sale_notes', models.TextField(blank=True, help_text='These notes will NOT appear in the table. They only appear in the admin panel.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_resigned'],
            },
        ),
    ]
