# Generated by Django 3.2.6 on 2022-02-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_resigned',
            field=models.DateField(blank=True, default='', help_text='Enter date of the certificate resignation. Format: YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_to',
            field=models.CharField(blank=True, help_text='Enter the name of the person or entity the certificate was sold to. If there is no name in this blank, the certificate will appear in the for sale table on the website. Format: YYYY-MM-DD.', max_length=100, null=True),
        ),
    ]
