# Generated by Django 3.2.6 on 2021-09-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20210905_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_create'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
