# Generated by Django 3.2.6 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MembershipApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deed_owner_names", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("phone_1", models.CharField(max_length=50)),
                ("phone_2", models.CharField(blank=True, max_length=50)),
                ("primary_address", models.CharField(blank=True, max_length=255)),
                ("previous_owner_names", models.CharField(blank=True, max_length=255)),
                ("membership_number", models.CharField(blank=True, max_length=100)),
                ("key_number", models.CharField(blank=True, max_length=100)),
                (
                    "tenant_names_contact",
                    models.TextField(
                        blank=True,
                        help_text="If home is rented, provide tenant names and contact information.",
                    ),
                ),
                ("badge_1_name", models.CharField(max_length=255)),
                ("badge_1_phone", models.CharField(blank=True, max_length=50)),
                ("badge_1_email", models.EmailField(blank=True, max_length=254)),
                ("badge_2_name", models.CharField(blank=True, max_length=255)),
                ("badge_2_phone", models.CharField(blank=True, max_length=50)),
                ("badge_2_email", models.EmailField(blank=True, max_length=254)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("-submitted_at",)},
        ),
    ]
