# Generated by Django 3.2.6 on 2021-09-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='feature_title',
        ),
    ]
