# Generated by Django 3.2.6 on 2021-09-25 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_feature_featured_flyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="You can say, 'Alert', 'Important', 'Important Pool Information', etc.", max_length=250)),
                ('slug', models.SlugField(help_text="This field automatically populates as you type in the title. It's needed to distinguish it from other alerts.", max_length=250, unique_for_date='publish')),
                ('text', models.TextField(blank=True, help_text='Just enter text you want in the alert. To make a link use this format: [text](full website address) NO SPACE BETWEEN BRACKETS AND PARENTHESIS - Example for email contact: [Email Bill Ross](mailto:listmanager@cylrc.org).  **text** will show up as bold type.', null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, help_text="Use now, or 'today'. If you are featuring more than one Alert on the homepage, the date that is closest to 'now' will appear first on the page.")),
                ('alert_color', models.CharField(choices=[('blue', 'blue'), ('gray', 'gray'), ('green', 'green'), ('redpink', 'redpink'), ('yellow', 'yellow'), ('ltblue', 'ltblue'), ('white', 'white'), ('darkgray', 'darkgray')], default='redpink', help_text='This is the color the box and fill around your alert will be.  It defaults to redpink.', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, help_text="You don't need to do anything here. It's automatic.")),
                ('updated', models.DateTimeField(auto_now=True, help_text="You don't need to do anything here. It's automatic.")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='If set to Draft, the alert will not appear. If set to Published, the alert will appear.', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='If set to Draft, the alert will not appear. If set to Published, the alert will appear.', max_length=10),
        ),
    ]
