# Generated by Django 3.2.6 on 2021-09-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210925_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_color',
            field=models.CharField(choices=[('primary', 'Sky Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Reddish-Pink'), ('warning', 'Yellow'), ('info', 'Light Blue'), ('light', 'White'), ('dark', 'Dark Gray')], default='danger', help_text='This is the color the box and fill around your alert will be.  It defaults to Reddish-Pink.', max_length=10),
        ),
    ]
