# Generated by Django 3.2.6 on 2021-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_alert_alert_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='expire',
            field=models.DateTimeField(blank=True, help_text="Expiration feature not working yet. For now, you will have to go back in and change Status to 'Draft'", null=True),
        ),
    ]
