# Generated by Django 3.2.6 on 2021-09-25 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alert_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='expire',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Expiration feature not working yet. For now, you will have to go back in and change Status to 'Draft'"),
        ),
    ]
