# Generated by Django 3.2.6 on 2021-09-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210925_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(help_text="This field automatically populates as you type in the title. It's needed to distinguish it from other featured FLYERS.", max_length=250, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(help_text='What is the title of your Featured activity?', max_length=250),
        ),
    ]
