# Generated by Django 3.2.6 on 2021-09-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210925_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_location',
            field=models.CharField(blank=True, default=None, help_text="If you put something here, it will appear on the site. You can leave it blank if it's at the Club.", max_length=250),
        ),
    ]
