# Generated by Django 3.2.6 on 2021-10-02 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_feature_feature_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBulletinBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="You can say, 'Leaders Required', 'Important', 'Yard Sale Help Needed', etc.", max_length=250)),
                ('slug', models.SlugField(help_text="This field automatically populates as you type in the title of your pinned note. It's needed to distinguish it from other pinned notes.", max_length=250, unique_for_date='publish')),
                ('text', models.TextField(blank=True, help_text='Just enter text you want in the pinned note. To make a link use this format: [text](full website address) NO SPACE BETWEEN BRACKETS AND PARENTHESIS - Example for email contact: [Email Monica Hall](mailto:rlmhall2@gmail.com).  **text** will show up as bold type.', null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, help_text="When do you want the pinned note to appear? If you are featuring more than one pinned note on the activity page, the date that is closest to 'now' will appear first on the page.")),
                ('expire', models.DateTimeField(default=django.utils.timezone.now, help_text='Put in the day/time you would like for this pinned note to expire (no longer show up on the site).')),
                ('paper_color', models.CharField(choices=[('primary', 'Sky Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Reddish-Pink'), ('warning', 'Yellow'), ('info', 'Light Blue'), ('light', 'White'), ('dark', 'Dark Gray')], default='danger', help_text='This is the color of the paper your pinned note will be.  It defaults to Reddish-Pink.', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, help_text="You don't need to do anything here. It's automatic.")),
                ('updated', models.DateTimeField(auto_now=True, help_text="You don't need to do anything here. It's automatic.")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='If set to Draft, the pinned note will NEVER appear. If set to Published, the pinned note will appear between the set Publish and Expire dates.', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
