# Generated by Django 3.2.6 on 2023-02-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_activitybulletinboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('-feature_day_time',)},
        ),
    ]
