# Generated by Django 3.2.6 on 2023-02-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_feature_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_landscape',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
