# Generated by Django 3.2.6 on 2021-08-21 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_club_held',
            field=models.BooleanField(default=False, help_text='This is usually true when a member surrenders the certificate to the club without selling. Check if true. Leave blank if false.'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_for_sale',
            field=models.BooleanField(default=False, help_text='Check if true. Leave blank if false.'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_for_sale_as_of_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter date the certificate is for sale.  It defaults to now.'),
        ),
    ]
