# Generated by Django 3.2.6 on 2021-08-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20210820_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='is_for_sale_as_of_date',
            field=models.DateTimeField(blank=True, default=False, help_text='Enter date the certificate is for sale.  It defaults to now.'),
        ),
    ]
