# Generated by Django 3.2.6 on 2021-08-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificate_is_for_sale_as_of_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='is_for_sale_as_of_date',
            field=models.DateField(blank=True, default=False, help_text='Enter date the certificate is for sale.  It defaults to now.', null=True),
        ),
    ]
