# Generated by Django 3.2.6 on 2021-08-21 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_auto_20210820_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='purchase_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
