# Generated by Django 3.2.6 on 2021-08-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_myprofile_member_coyote_lakes_qualifying_address'),
        ('certificates', '0009_alter_certificate_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='name_associated_with_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_associated_with_certificate', to='accounts.myprofile'),
        ),
    ]
