# Generated by Django 3.2.6 on 2021-08-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_myprofile_member_coyote_lakes_qualifying_address'),
        ('certificates', '0010_certificate_name_associated_with_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name_associated_with_certificate',
            field=models.ForeignKey(blank=True, help_text='If the name associated is not in the dropbox, you have to add them to the Users table first, then the MyProfile table.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_associated_with_certificate', to='accounts.myprofile'),
        ),
    ]
