# Generated by Django 3.2.6 on 2021-08-21 15:39

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20210820_0950'),
        ('certificates', '0011_alter_certificate_name_associated_with_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='member_coyote_lakes_address',
            field=address.models.AddressField(blank=True, help_text='Enter the Coyote Lakes address associated with the certificate number.  If the address does not exist in the dropdown, it needs to be added in the Certificate table.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_coyote_lakes_address', to='address.address'),
        ),
    ]
