# Generated by Django 3.2.6 on 2021-08-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_alter_certificate_member_coyote_lakes_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['certificate_number']},
        ),
    ]
