# Generated by Django 3.2.6 on 2021-08-23 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_myprofile_user'),
        ('certificates', '0017_auto_20210822_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name_associated_with_certificate',
            field=models.ForeignKey(blank=True, help_text='Choose one only. If you need to identify another person, put it in the notes. If the main name/owner associated is not in the dropbox, you have to add the user account. See instructions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='name_associated_with_certificate', to='accounts.myprofile'),
        ),
    ]
