# Generated by Django 3.2.6 on 2021-09-07 13:20

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20210820_0950'),
        ('certificates', '0018_alter_certificate_name_associated_with_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='member_coyote_lakes_address',
            field=address.models.AddressField(blank=True, help_text='Enter the Coyote Lakes address associated with the certificate number. If the certificate does not have an address associated with it, use the club address.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_coyote_lakes_address', to='address.address'),
        ),
    ]
