# Generated by Django 3.2.6 on 2021-09-26 23:11

import address.models
import certificates.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20210820_0950'),
        ('certificates', '0019_alter_certificate_member_coyote_lakes_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.PositiveIntegerField(default=certificates.models.from_10218, editable=False, help_text='This number is auto-generated', unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='member_coyote_lakes_address',
            field=address.models.AddressField(help_text='Enter the Coyote Lakes address associated with the certificate number. If the certificate does not have an address associated with it, use the club address.', on_delete=django.db.models.deletion.CASCADE, related_name='member_coyote_lakes_address', to='address.address'),
        ),
    ]
