# Generated by Django 3.2.6 on 2021-10-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0020_auto_20210926_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='exclude',
            field=models.BooleanField(default=False, help_text='Check if you want to exclude this certificate from the Home Lookup Search on the website.'),
        ),
    ]
