# Generated by Django 3.2.6 on 2021-12-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_myprofile_member_coyote_lakes_qualifying_address'),
        ('certificates', '0021_certificate_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name_associated_with_certificate',
            field=models.ForeignKey(blank=True, help_text='Choose one only. If you need to identify another person, put it in the notes. If the main name/owner associated is not in the dropbox, you have to add the user account. See instructions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_associated_with_certificate', to='accounts.myprofile'),
        ),
    ]
