# Generated by Django 3.2.6 on 2022-01-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0024_alter_certificate_name_associated_with_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name_associated_with_certificate',
            field=models.CharField(blank=True, help_text='Enter a name that associates this certificate to a member or members.', max_length=100, null=True),
        ),
    ]
