# Generated by Django 3.2.6 on 2021-08-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myprofile',
            options={'managed': True},
        ),
    ]
