# Generated by Django 3.2.6 on 2021-08-21 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='about_me',
            field=models.CharField(blank=True, max_length=250, verbose_name='about_me'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='date_entered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='date_first_entered',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter date first entered from old table information.'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='favorite_activity',
            field=models.CharField(blank=True, max_length=125, verbose_name='favorite_activity'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='member_notes',
            field=models.TextField(blank=True, verbose_name='member_notes'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='title',
            field=models.CharField(blank=True, help_text='i.e. Dr., Mr., etc. Can be left blank', max_length=4),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='favorite_snack',
            field=models.CharField(blank=True, max_length=125, verbose_name='favorite_snack'),
        ),
    ]
