# Generated by Django 3.2.6 on 2021-08-21 03:31

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myprofile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='cell_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='cell_phone', max_length=31),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='other_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='other_phone', max_length=31),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='sub_title',
            field=models.CharField(blank=True, help_text='i.e. Jr., III, etc. Can be left blank', max_length=4),
        ),
    ]
