# Generated by Django 3.2.6 on 2021-08-21 04:03

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210820_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='date_entered',
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='cell_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Cell Phone Number', max_length=31),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='other_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Other Number (i.e., home, work)', max_length=31),
        ),
    ]
