# Generated by Django 3.2.6 on 2021-08-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210822_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='birthdate',
            field=models.DateField(blank=True, help_text="We don't disclose the year. Enter if you'd like to be on our birthday lists.", null=True),
        ),
    ]
