# Generated by Django 3.2.6 on 2021-08-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_myprofile_birthdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myprofile',
            options={'managed': True, 'ordering': ['user']},
        ),
    ]
