# Generated by Django 3.2.6 on 2021-08-23 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_myprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myprofile',
            options={'managed': True},
        ),
    ]
