# Generated by Django 3.2.6 on 2021-08-27 16:45

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_myprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='cell_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='other_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
