# Generated by Django 3.2.6 on 2021-08-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210827_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='favorite_activity',
            field=models.TextField(blank=True, help_text='    ', verbose_name='favorite activity'),
        ),
    ]
