# Generated by Django 3.2.6 on 2021-08-27 17:16

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_myprofile_favorite_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='about_me',
            field=models.TextField(blank=True, help_text='    ', verbose_name='about me'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='birthdate',
            field=models.DateField(blank=True, help_text="Format: YYYY-MM-DD. We don't disclose the year. Enter if you'd like to be on our birthday lists.", null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='cell_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='    ', max_length=31),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='other_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='    ', max_length=31),
        ),
    ]
