# Generated by Django 3.2.6 on 2021-08-29 23:27

from django.db import migrations
import easy_thumbnails.fields
import userena.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210827_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='mugshot',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Automatically crops. Image should be greater than 430 pixels wide. Regular cell phone photos work great.', upload_to=userena.models.upload_to_mugshot, verbose_name='Member Photo'),
        ),
    ]
