# Generated by Django 3.2.6 on 2021-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_myprofile_mugshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='temporary_password',
            field=models.CharField(default='pa$$word', help_text="Enter the temporary password you provided to create this user's account.", max_length=25),
        ),
    ]
