# Generated by Django 3.2.6 on 2021-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_myprofile_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='temporary_password',
            field=models.CharField(default='pa$$word', help_text="Enter the temporary password you provided to create this user's account. If other than pa$$word, change to the actual temporary password.", max_length=25),
        ),
    ]
