# Generated by Django 3.2.6 on 2021-09-11 23:32

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_myprofile_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='cell_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='    ', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='other_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='    ', max_length=31, null=True),
        ),
    ]
