# Generated by Django 3.2.6 on 2021-09-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_myprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='cell_phone',
            field=models.CharField(blank=True, help_text='    ', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='other_phone',
            field=models.CharField(blank=True, help_text='    ', max_length=31, null=True),
        ),
    ]
