# Generated by Django 3.2.6 on 2021-09-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_myprofile_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='birth_day',
            field=models.CharField(blank=True, choices=[('--', '--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default='--', help_text='   ', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='birth_month',
            field=models.CharField(blank=True, choices=[('--', '--'), ('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default='--', help_text='   ', max_length=10, null=True),
        ),
    ]
