# Generated by Django 3.2.6 on 2021-09-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210919_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='birth_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='   ', max_length=10, null=True),
        ),
    ]
