# Generated by Django 3.2.6 on 2021-09-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_myprofile_birth_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='birthdate',
        ),
    ]
