# Generated by Django 3.2.6 on 2021-09-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_myprofile_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='birthdate',
        ),
    ]
