# Generated by Django 3.2.6 on 2021-09-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20210919_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='birth_month',
        ),
    ]
