# Generated by Django 3.2.6 on 2021-09-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_myprofile_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='temporary_password',
            field=models.CharField(blank=True, help_text="Enter the temporary password you provided to create this user's account. Be EXACT since they will use this password to log in for the first time.", max_length=25, null=True),
        ),
    ]
