# Generated by Django 3.2.6 on 2022-01-06 15:00

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('accounts', '0050_alter_myprofile_member_part_time_away_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='member_part_time_away_address',
            field=address.models.AddressField(blank=True, help_text='Only enter if this profile has two homes and go away for summer, but they hold the Coyote Lakes membership, not a renter; enter their away address here. Leave blank if does not apply.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_part_time_away_address', to='address.address'),
        ),
    ]
