# Generated by Django 3.2.6 on 2022-01-10 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0025_alter_certificate_name_associated_with_certificate'),
        ('accounts', '0052_alter_myprofile_member_coyote_lakes_qualifying_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='member_coyote_lakes_qualifying_address',
            field=models.ForeignKey(blank=True, help_text='Choose address from dropdown, if applies to this profile.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_coyote_lakes_qualifying_address', to='certificates.certificate'),
        ),
    ]
