# Generated by Django 3.2.6 on 2022-09-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0002_alter_balance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='cert',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
