# Generated by Django 3.2.6 on 2022-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0003_alter_balance_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='cert',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
