# Generated by Django 3.2.6 on 2022-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0004_alter_balance_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.CharField(blank=True, max_length=30, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='cert',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='cert'),
        ),
    ]
