# Generated by Django 3.2.6 on 2021-11-04 03:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0047_myprofile_exclude_member_coyote_lakes_address_from_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')])),
                ('theme_description', models.TextField()),
                ('picture', models.BinaryField(editable=True, null=True)),
                ('content_type', models.CharField(help_text='The MIMEType of the file', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comms', models.ManyToManyField(related_name='comms_owned', through='tables.Comm', to=settings.AUTH_USER_MODEL)),
                ('guest_five', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_five', to='accounts.myprofile')),
                ('guest_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_four', to='accounts.myprofile')),
                ('guest_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_one', to='accounts.myprofile')),
                ('guest_seven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_seven', to='accounts.myprofile')),
                ('guest_six', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_six', to='accounts.myprofile')),
                ('guest_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_three', to='accounts.myprofile')),
                ('guest_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_two', to='accounts.myprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comm',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
    ]
