# Generated by Django 3.2.6 on 2021-11-04 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='guest_five',
        ),
        migrations.RemoveField(
            model_name='table',
            name='guest_four',
        ),
        migrations.RemoveField(
            model_name='table',
            name='guest_one',
        ),
        migrations.RemoveField(
            model_name='table',
            name='guest_seven',
        ),
        migrations.RemoveField(
            model_name='table',
            name='guest_six',
        ),
        migrations.RemoveField(
            model_name='table',
            name='guest_three',
        ),
        migrations.RemoveField(
            model_name='table',
            name='guest_two',
        ),
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
        migrations.AddField(
            model_name='table',
            name='name_for_seat_eight',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name_for_seat_five',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name_for_seat_four',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name_for_seat_one',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name_for_seat_seven',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name_for_seat_six',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name_for_seat_three',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name_for_seat_two',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='table_name',
            field=models.CharField(default='Snowy Christmas', help_text='Name your table based on the theme', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='picture',
            field=models.BinaryField(editable=True, help_text='Add a picture of your table inspiration, if you like.', null=True),
        ),
    ]
