# Generated by Django 3.2.6 on 2021-11-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20211103_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name_for_seat_eight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name_for_seat_five',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name_for_seat_four',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name_for_seat_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name_for_seat_seven',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name_for_seat_six',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name_for_seat_three',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name_for_seat_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
