# Generated by Django 3.2.6 on 2021-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The end time must be later than the start time.', verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, db_index=True, verbose_name='start'),
        ),
    ]
