# Generated by Django 3.2.6 on 2021-08-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20210814_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='need_volunteers',
            field=models.BooleanField(default=False, verbose_name='need volunteers'),
        ),
    ]
