# Generated by Django 3.2.6 on 2021-08-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_occurrence_need_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='need_volunteers',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='dish',
            field=models.BooleanField(default=False, help_text='Check if you would like for members to sign up to bring a dish.  Be sure to have the details of dish ideas in your description.', verbose_name='need volunteers'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='rsvp',
            field=models.BooleanField(default=False, help_text='Check if you would like for members to let you know they are coming.', verbose_name='need volunteers'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='volunteers',
            field=models.BooleanField(default=False, help_text='Check if you would like to have volunteers for this occassion.', verbose_name='need volunteers'),
        ),
    ]
