# Generated by Django 3.2.6 on 2021-08-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_rename_volunteers_occurrence_need_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='dish',
            field=models.BooleanField(default=False, help_text='Check if you would like for members to sign up to bring a dish.  Be sure to have the details of dish ideas in your description.', verbose_name='member brings dish'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='rsvp',
            field=models.BooleanField(default=False, help_text='Check if you would like for members to let you know they are coming.', verbose_name='member rsvp'),
        ),
    ]
