# Generated by Django 3.2.6 on 2021-08-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_alter_occurrence_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='dish',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='bring',
            field=models.BooleanField(default=False, help_text='Check if you would like for members to sign up to bring a dish or item.  Be sure to have the details of dish or item ideas in your description.', verbose_name='member brings dish or item'),
        ),
    ]
