# Generated by Django 3.2.6 on 2021-08-31 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_auto_20210830_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='event',
            new_name='occurrence',
        ),
    ]
