# Generated by Django 3.2.6 on 2021-08-31 02:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0024_rename_event_volunteer_occurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='volunteers',
            field=models.ManyToManyField(related_name='volunteers_owned', through='schedule.Volunteer', to=settings.AUTH_USER_MODEL),
        ),
    ]
