# Generated by Django 3.2.6 on 2021-08-31 21:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0025_alter_occurrence_volunteers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='rsvp',
            new_name='want_rsvp',
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(default=False, help_text='   ')),
                ('bringing', models.TextField(blank=True, help_text='If you are attending, please indicate what you may bring based on the request in the description of this event (i.e., dish, item for yard sale, etc.)', null=True, validators=[django.core.validators.MinLengthValidator(3, 'Text must be greater than 3 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.occurrence')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='occurrence',
            name='rsvps',
            field=models.ManyToManyField(related_name='rsvps_owned', through='schedule.Rsvp', to=settings.AUTH_USER_MODEL),
        ),
    ]
