# Generated by Django 3.2.6 on 2021-08-31 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0026_auto_20210831_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rsvp',
            new_name='Memberrsvp',
        ),
        migrations.RenameField(
            model_name='occurrence',
            old_name='want_rsvp',
            new_name='rsvp',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='rsvps',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='memberrsvps',
            field=models.ManyToManyField(related_name='memberrsvps_owned', through='schedule.Memberrsvp', to=settings.AUTH_USER_MODEL),
        ),
    ]
