# Generated by Django 3.2.6 on 2021-09-01 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_auto_20210831_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrsvp',
            name='bringing',
            field=models.TextField(blank=True, default='', help_text='If you are attending, please indicate what you may bring based on the request in the description of this event (i.e., dish, item for yard sale, etc.)', null=True, validators=[django.core.validators.MinLengthValidator(3, 'Text must be greater than 3 characters')]),
        ),
    ]
