# Generated by Django 3.2.6 on 2021-09-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_alter_memberrsvp_bringing'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='exclude',
            field=models.BooleanField(default=False, help_text='Check if you do NOT want this event to show up on the activity list page (it will still show up on the calendar).', verbose_name='exclude from list'),
        ),
    ]
