# Generated by Django 3.2.6 on 2021-09-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0030_occurrence_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='description',
            field=models.TextField(blank=True, help_text='In your description, let everyone know details about the event. No need to put Date or Time as this will automatically appear. Indicate what members need to bring, if applies.  To make a link use this format: [text](full website address) - Example for reservation link: [RSVP Requested](https://www.coyotelakesrecreationclub.org/activity/respond). Example for Volunteer link: [Volunteers Needed](https://www.coyotelakesrecreationclub.org/activity/vol). Example for email contact: [Email Monica Hall](mailto:rlmhallmi@yahoo.com).  **text** will show up as bold type. A dash (-) before items in a list will format as a list.', verbose_name='description'),
        ),
    ]
