# Generated by Django 3.2.6 on 2021-10-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0032_alter_occurrence_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exclude',
            field=models.BooleanField(default=False, help_text='Check if you do NOT want this event to show up on the activity list page (it will still show up on the calendar).', verbose_name='exclude from list'),
        ),
    ]
