# Generated by Django 3.2.6 on 2021-11-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0033_event_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrsvp',
            name='guests',
            field=models.TextField(blank=True, default='', help_text='Please indicate in this box the names of guests you plan to bring and whether or not they are club members or OUTSIDE of Coyote Lakes neighborhood.', null=True),
        ),
    ]
