# Generated by Django 3.2.6 on 2021-11-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0034_memberrsvp_guests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberrsvp',
            options={'ordering': ('owner__last_name',)},
        ),
        migrations.AddField(
            model_name='memberrsvp',
            name='mealchoice',
            field=models.CharField(choices=[('------', '------'), ('Chicken', 'Chicken'), ('Tri-Tip', 'Tri-Tip')], default='------', help_text='Select your meal.', max_length=10),
        ),
    ]
