# Generated by Django 3.2.6 on 2021-11-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0035_auto_20211112_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrsvp',
            name='mealchoice',
            field=models.CharField(choices=[('------', '------'), ('Basket', 'Basket'), ('Decadent Dessert', 'Decadent Dessert'), ('Service', 'Service'), ('None - Maybe Next Year', 'None - Maybe Next Year')], default='------', help_text='Which item will you bring for fundraising silent auction?', max_length=30),
        ),
    ]
