# Generated by Django 3.2.6 on 2021-08-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number_one', models.PositiveIntegerField(help_text='This number may not be greater than 2147483647', unique=True)),
                ('key_number_two', models.PositiveIntegerField(blank=True, help_text='This number may not be greater than 2147483647', null=True)),
                ('key_notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('member_coyote_lakes_qualifying_address_for_keys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_coyote_lakes_qualifying_address_for_keys', to='certificates.certificate')),
            ],
        ),
    ]
