# Generated by Django 3.2.6 on 2021-08-22 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0015_alter_certificate_member_coyote_lakes_address'),
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='member_coyote_lakes_qualifying_address_for_keys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_coyote_lakes_qualifying_address_for_keys', to='certificates.certificate'),
        ),
    ]
