# Generated by Django 3.2.6 on 2021-08-26 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0018_alter_certificate_name_associated_with_certificate'),
        ('keys', '0003_auto_20210825_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='member_coyote_lakes_qualifying_address_for_keys',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_coyote_lakes_qualifying_address_for_keys', to='certificates.certificate'),
        ),
    ]
