# Generated by Django 3.2.6 on 2021-08-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0018_alter_certificate_name_associated_with_certificate'),
        ('keys', '0004_alter_key_member_coyote_lakes_qualifying_address_for_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='member_coyote_lakes_qualifying_address_for_keys',
        ),
        migrations.AddField(
            model_name='key',
            name='certificate_and_qualifying_address_for_keys',
            field=models.OneToOneField(blank=True, help_text='If certificate needed does not appear, it needs to be created first.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_and_qualifying_address_for_keys', to='certificates.certificate'),
        ),
    ]
