# Generated by Django 3.2.6 on 2021-12-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0022_alter_certificate_name_associated_with_certificate'),
        ('keys', '0005_auto_20210826_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='certificate_and_qualifying_address_for_keys',
            field=models.OneToOneField(blank=True, help_text='If certificate needed does not appear, it needs to be created first.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_and_qualifying_address_for_keys', to='certificates.certificate'),
        ),
    ]
