# Generated by Django 3.2.6 on 2022-01-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0023_alter_certificate_name_associated_with_certificate'),
        ('keys', '0007_alter_key_certificate_and_qualifying_address_for_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='certificate_and_qualifying_address_for_keys',
            field=models.OneToOneField(blank=True, help_text='If certificate needed does not appear, it needs to be created first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_and_qualifying_address_for_keys', to='certificates.certificate'),
        ),
    ]
