# Generated by Django 3.2.6 on 2021-09-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0046_alter_myprofile_temporary_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('members', models.ManyToManyField(to='accounts.MyProfile')),
            ],
        ),
    ]
