# Generated by Django 3.2.6 on 2021-09-27 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 27, 17, 58, 54, 517055, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
