# Generated by Django 3.2.6 on 2021-09-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20210927_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='issue_date',
            new_name='print_date',
        ),
    ]
