# Generated by Django 3.2.6 on 2021-09-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_rename_issue_date_badge_print_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_color',
            field=models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('white', 'No Color')], default='blue', max_length=10),
        ),
    ]
