# Generated by Django 3.2.6 on 2021-09-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_badge_badge_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_color',
            field=models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('white', 'No Color')], default='blue', max_length=10),
        ),
    ]
